version: "3.9"
services:
  api:
    build: .
    environment:
      - AI_CACHE_ROOT=/warehouse/cache
      - API_CORS_ORIGINS=http://localhost:3000
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - /warehouse/cache:/warehouse/cache
    ports: ["8000:8000"]
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    depends_on: [redis]
  worker:
    build: .
    environment:
      - AI_CACHE_ROOT=/warehouse/cache
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - /warehouse/cache:/warehouse/cache
    command: celery -A workers.celery_app:celery_app worker --loglevel=INFO
    depends_on: [redis]
  redis:
    image: redis:7
    ports: ["6379:6379"]
