# configs/train/dreambooth.yaml - DreamBooth training config
model:
  model_id: "runwayml/stable-diffusion-v1-5"
  revision: null

training:
  resolution: 768
  train_batch_size: 1
  gradient_accumulation_steps: 4
  learning_rate: 5e-6
  lr_scheduler: "constant"
  lr_warmup_steps: 0
  max_train_steps: 1000
  checkpointing_steps: 500

dreambooth:
  instance_prompt: "a photo of sks person"
  class_prompt: "a photo of person"
  instance_data_dir: "${AI_CACHE_ROOT}/datasets/dreambooth/instance"
  class_data_dir: "${AI_CACHE_ROOT}/datasets/dreambooth/class"
  num_class_images: 200
  prior_loss_weight: 1.0

optimization:
  mixed_precision: "fp16"
  gradient_checkpointing: true
  use_8bit_adam: true
  train_text_encoder: false

output:
  output_dir: "${AI_CACHE_ROOT}/models/dreambooth"
  save_model_card: true
